# ARD_HOME=/usr/share/arduino
# ARD_BIN=/usr/bin
# BOARD = uno
# PORT = /dev/ttyUSB0
# MON_SPEED = 115200
# # INC_DIRS = ../common
# # LIB_DIRS = ../libraries/Task ../../libraries/VirtualWire
# include ../Makefile.master
#
BOARD_TAG=uno
ARDUINO_PORT=/dev/ttyUSB*
ARDUINO_DIR=/usr/share/arduino
ARDMK_DIR=../Arduino-Makefile

include ../Arduino-Makefile/arduino-mk/Arduino.mk

