# NOTE: you must either name your main file ending in .ino
# 	or #include <Arduino.h> 
# 	for things to compile correctly.

BOARD_TAG=uno
ARDUINO_PORT=/dev/ttyUSB*
ARDUINO_DIR=/usr/share/arduino
ARDMK_DIR=../Arduino-Makefile

include ../Arduino-Makefile/arduino-mk/Arduino.mk

